# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java samples CI 

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      name:
        description: 'manual build trigger'
      home:
        description: 'location'
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Cache Gradle packages
      uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: ${{ runner.os }}-gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: clean
      run: ./gradlew clean
    - name: assemble debug
      run: ./gradlew assembleDebug
    - name: unit tests
      run: ./gradlew testDebugUnitTest
    - name: lint
      run: ./gradlew lintDebug
    - name: pmd
      run: ./gradlew CompanionPane:pmd CompanionPaneLevel2:pmd DragAndDrop:pmd DualView:pmd ExtendCanvas:pmd IntentToSecondScreen:pmd ListDetail:pmd MultipleInstances:pmd OrientationAndSpanning:pmd PenEvents:pmd TwoPage:pmd
    - name: checkstyle
      run: ./gradlew CompanionPane:checkstyle CompanionPaneLevel2:checkstyle DragAndDrop:checkstyle DualView:checkstyle ExtendCanvas:checkstyle IntentToSecondScreen:checkstyle ListDetail:checkstyle MultipleInstances:checkstyle OrientationAndSpanning:checkstyle PenEvents:checkstyle TwoPage:checkstyle
